# Generated by Django 4.0.4 on 2022-05-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('sigla_estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.cliente')),
                ('motocicleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendas.motocicleta')),
            ],
        ),
    ]
