# Generated by Django 4.0.5 on 2022-06-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='motocicleta',
            name='ano',
            field=models.IntegerField(default=2005),
            preserve_default=False,
        ),
    ]
