# Generated by Django 4.0.5 on 2022-06-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_motocicleta_ano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='data',
            new_name='data_compra',
        ),
    ]
